# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "C:\\Projects\\Web-API"
      dockerfile: "API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/API.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/API.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Даниил\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\Web-API\\API:/app:rw"
    - "C:\\Projects\\Web-API:/src:rw"
    working_dir: "/app"
